services:
  - type: web
    name: ohoster-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.0"
