services:
  - type: web
    name: hosting-bot-2
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        value: 8964647336:AAEoMHcCKOeMU37VasxqbWItyFIFUg4mGFQ
      - key: PORT
        value: "10000"
      - key: PYTHON_VERSION
        value: "3.11.0"
